### ISSUE TITLE
Discussion: Features

### ISSUE THREAD

**Issue by cherylli** [webdev-20/the-lassie-lounge-hacktoberfest-project-2022#5]
**Task**
Decide on the Features

**Must Have**
- url shortening (frontend and backend API)

**Should Have**
Landing Page

**Good to Have**
User Accounts

Any other suggestions?

**Comment by cherylli** [comment]
# Must Have
- [ ] url shortening
  - [ ] (backend) schema
  - [ ] (backend) endpoint - create (long url to code)
  - [ ] (backend) endpoint - read (code to long url)
  - [ ] (backend) endpoint - delete 
  - [ ] (backend) error handling for invalid code
  - [ ] (frontend) component to enter url
  - [ ] (f) api call to create code from long url
  - [ ] (f) component to show previous shortened urls
- [ ] A design

# Should Have
- [ ] landing page (desktop/tablet/mobile)
  - [ ] logo
  - [ ] nav bar (desktop and mobile)
  - [ ] hero component
  - [ ] footer
  - [ ] social media icons
- [ ] user accounts (so they can access/manage their old links)
  - [ ] (b) user schema
  - [ ] (b) probably use passport with jwt/google account/other account login strategies
  - [ ] (b) login endpoint
  - [ ] (b) register endpoint
  - [ ] (f) login api call
  - [ ] (f) register api call
  - [ ] (f) logout api call
  - [ ] (f) handle login state with maybe local storage 


# Good to Have
- [ ] Extra Pages (mostly fake information)
  - [ ] features
  - [ ] pricing

**Comment by gschadegg** [comment]
Additional Feature ideas:

- track number times shortened url is clicked
- track referrer

**Comment by cherylli** [comment]
![image](https://user-images.githubusercontent.com/6191116/193699166-f5358ab7-bb21-4870-9569-58cc2a9d70e6.png)
![image](https://user-images.githubusercontent.com/6191116/193699182-cb645368-6381-4db2-b178-1648de0e6523.png)
